package gdx.kapotopia.AssetsManaging;

public enum UseFont {
    /* CLASSIC */
    CLASSIC_BOLD_NORMAL_BLACK,
    CLASSIC_BOLD_NORMAL_WHITE,
    CLASSIC_BOLD_NORMAL_YELLOW,
    CLASSIC_IT_NORMAL_BLACK,
    CLASSIC_IT_NORMAL_WHITE,
    CLASSIC_REG_BIG_BLACK,
    CLASSIC_REG_BIG_WHITE,
    CLASSIC_REG_NORMAL_BLACK,
    CLASSIC_REG_NORMAL_WHITE,
    CLASSIC_SANS_MIDDLE_BLACK,
    CLASSIC_SANS_SMALL_BLACK,
    CLASSIC_SANS_SMALL_WHITE,
    CLASSIC_SANS_NORMAL_BLACK,
    CLASSIC_SANS_NORMAL_WHITE,
    CLASSIC_SANS_NORMAL_GRAY,
    CLASSIC_SANS_NORMAL_YELLOW,
    /* AESTHETIC */
    AESTHETIC_SMALL_BLACK,
    AESTHETIC_SMALL_WHITE,
    AESTHETIC_NORMAL_BLACK,
    AESTHETIC_NORMAL_WHITE,
    AESTHETIC_TINY_BLACK
}
